name: 'Run dotenv-linter with reviewdog'
description: '🐶 Run dotenv-linter with reviewdog on pull requests to improve code review experience.'
author: 'mgrachev (reviewdog)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
  dotenv_linter_flags:
    description: 'dotenv-linter flags. (dotenv-linter <dotenv_linter_flags>)'
    default: ''
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'dotenv-linter'
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
    default: 'github-pr-check'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.dotenv_linter_flags }}
    - ${{ inputs.tool_name }}
    - ${{ inputs.level }}
    - ${{ inputs.reporter }}
branding:
  icon: 'check-circle'
  color: 'green'
